version: '3'

services:
  oncall-web:
    build: .
    hostname: oncall
    ports:
      - "8080:8080"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
      - SYNOLOGY_APP_ID=your_app_id
      - SYNOLOGY_REDIRECT_URI=your_redirect_uri
      - SYNOLOGY_OAUTH_URL=your_api_host
      - SYNOLOGY_SDK_URL=your_sdk_url

    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml
    networks:
      - iris
  
  oncall-mysql:
    hostname: oncall-mysql
    image: mysql:9.4
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - iris

networks:
  iris:
    name: iris
